# -*- coding: utf-8 -*-
"""DM-Dephasing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y3Zx5Vi-CxshD5_4_ewHYWRgq2XWtXQo
"""

"""
========================================================================
Fisher-matrix distinguishability of dark-matter dephasing mechanisms
in LISA observations of black-hole binaries.

Physics implemented EXACTLY from Boudon, Brax, Valageas & Wong,
arXiv:2305.18540 (Phys. Rev. D 108, 103517):

  Eq. (4.16)  vacuum SPA phase, leading + 1PN            (verified p.8)
  Eq. (4.18)  halo-gravity dephasing        ~ x^(-11/3)  (-3   PN)
  Eq. (4.19)  accretion dephasing:
                high-f regime  (prop. rho0) ~ x^(-16/3)  (-5.5 PN)
                low-f  regime  (prop. rho_a)~ x^(-13/3)  (-4   PN)
  Eq. (4.20)  dynamical-friction dephasing  ~ x^(-16/3) * [1 + log(f)]
  Eqs. (5.5)-(5.8)  regime thresholds f_acc,i , f_df,i^-, f_df,i^+
  Eq. (5.3)   phase-only Fisher matrix (amplitude decorrelated)

Noise: full Robson, Cornish & Liu 2019 (arXiv:1803.01944) analytic
LISA sensitivity, Eqs. (1),(10),(11),(14), incl. 4-yr galactic
confusion noise.

Scientific question:
  Existing literature forecasts whether a DM environment is DETECTABLE.
  Here we ask whether a detected dephasing can be ATTRIBUTED to a
  specific mechanism: the joint Fisher matrix over TWO simultaneous
  mechanism amplitudes (rho_A = accretion, rho_B = dynamical friction)
  yields an off-diagonal correlation coefficient r_AB that quantifies
  mechanism confusion.  |r_AB| -> 1 means the two models are
  observationally degenerate over the band.
========================================================================
"""

import numpy as np
import csv

# ----------------------------------------------------------------------
# Physical constants (SI)
# ----------------------------------------------------------------------
G     = 6.67430e-11        # m^3 kg^-1 s^-2
c     = 2.99792458e8       # m s^-1
Msun  = 1.98892e30         # kg
GCM3  = 1.0e3              # 1 g/cm^3 in kg/m^3
YR    = 3.15576e7          # s
FSTAR = 0.66               # critical-flux constant, Sec. II of 2305.18540

# ======================================================================
# 1.  LISA noise: Robson, Cornish & Liu (2019), arXiv:1803.01944
# ======================================================================
L_ARM  = 2.5e9             # m
F_STAR = 19.09e-3          # Hz  (c / 2 pi L)

# 4-yr galactic-confusion fit parameters, Table 1 of RCL
_CONF = dict(A=9.0e-45, alpha=0.138, beta=-221.0, kappa=521.0,
             gamma=1680.0, fk=0.00113)


def P_oms(f):
    """Optical-metrology single-link noise, RCL Eq. (10) [m^2/Hz]."""
    return (1.5e-11) ** 2 * (1.0 + (2.0e-3 / f) ** 4)


def P_acc(f):
    """Single test-mass acceleration noise, RCL Eq. (11) [m^2 s^-4/Hz]."""
    return (3.0e-15) ** 2 * (1.0 + (0.4e-3 / f) ** 2) \
        * (1.0 + (f / 8.0e-3) ** 4)


def S_conf(f):
    """Galactic confusion noise, RCL Eq. (14), 4-yr mission [1/Hz]."""
    p = _CONF
    return p['A'] * f ** (-7.0 / 3.0) \
        * np.exp(-f ** p['alpha'] + p['beta'] * f * np.sin(p['kappa'] * f)) \
        * (1.0 + np.tanh(p['gamma'] * (p['fk'] - f)))


def Sn_LISA(f):
    """Full sky-averaged LISA sensitivity, RCL Eq. (1) + confusion [1/Hz]."""
    inst = (10.0 / (3.0 * L_ARM ** 2)) \
        * (P_oms(f) + 4.0 * P_acc(f) / (2.0 * np.pi * f) ** 4) \
        * (1.0 + 0.6 * (f / F_STAR) ** 2)
    return inst + S_conf(f)

# ======================================================================
# 2.  Binary system
# ======================================================================
class Binary:
    def __init__(self, m1_Msun, m2_Msun):
        # convention m1 >= m2
        if m2_Msun > m1_Msun:
            m1_Msun, m2_Msun = m2_Msun, m1_Msun
        self.m1 = m1_Msun * Msun
        self.m2 = m2_Msun * Msun
        self.m = self.m1 + self.m2
        self.mu = self.m1 * self.m2 / self.m
        self.nu = self.mu / self.m
        self.Mc = self.nu ** 0.6 * self.m

    # -- characteristic frequencies -----------------------------------
    def f_isco(self):
        return c ** 3 / (6.0 ** 1.5 * np.pi * G * self.m)

    def f_gamma(self):
        """v^2 = 0.137 c^2 relativistic-validity cut (Sec. IV.B.5)."""
        return 0.137 ** 1.5 * c ** 3 / (np.pi * G * self.m)

    def f_obs(self, Tobs=4.0 * YR):
        """GW frequency Tobs before merger (paper Sec. VI.A)."""
        return 4.149e-5 * (self.Mc / (1e6 * Msun)) ** (-5.0 / 8.0) \
            * (Tobs / YR) ** (-3.0 / 8.0)

    def lisa_band(self):
        """Boudon Table I: fmin = max(2e-5, f_obs); fmax = min(1, f_gamma)."""
        fmin = max(2.0e-5, self.f_obs())
        fmax = min(1.0, self.f_gamma())
        return fmin, fmax

    # -- regime thresholds, Eqs. (5.5)-(5.8) inverted for f -----------
    def f_acc(self, i, y):
        """Accretion threshold frequency for BH i (1 or 2)."""
        mi = self.m1 if i == 1 else self.m2
        return c ** 3 * mi ** 3 \
            / (3.0 * np.pi * FSTAR * G * self.m * self.mu ** 3 * y)

    def f_df_minus(self, y):
        """Lower dynamical-friction threshold for the smaller BH."""
        return c ** 3 * self.m2 ** 3 \
            / (np.pi * G * self.m * self.mu ** 3 * y ** 1.5)

    def _log_fdf_plus_y1(self):
        """log of f_df^+ at y = 1 (computed in log space: mu^15 etc.
        overflow float64 for supermassive systems)."""
        return (3.0 + 3.0 * np.log(c) + 5.0 * np.log(self.m)
                + 15.0 * np.log(self.mu) - np.log(5832.0 * np.pi * G)
                - 21.0 * np.log(self.m2))

    def f_df_plus(self, y):
        """Upper dynamical-friction threshold for the smaller BH."""
        return np.exp(self._log_fdf_plus_y1() - 1.5 * np.log(y))

    def y_for_fdf_plus(self, f_plus):
        """Invert f_df_plus(y) = f_plus  ->  density ratio y = rho_a/rho0."""
        return np.exp((2.0 / 3.0) * (self._log_fdf_plus_y1() - np.log(f_plus)))

# ======================================================================
# 3.  Phase model  (all Psi in radians; x = pi G Mc f / c^3)
# ======================================================================
def x_of_f(f, b):
    return np.pi * G * b.Mc * f / c ** 3


def psi_vacuum(f, b):
    """Eq. (4.16): leading + 1PN SPA phase."""
    x = x_of_f(f, b)
    onePN = (20.0 / 9.0) * (743.0 / 336.0 + 2.75 * b.nu) \
        * (np.pi * G * b.m * f / c ** 3) ** (2.0 / 3.0)
    return (3.0 / 128.0) * x ** (-5.0 / 3.0) * (1.0 + onePN)


def _dm_prefac(b, rho0_gcm3):
    """Common factor  rho0 G^3 Mc^2 / c^6  [dimensionless * s^0]."""
    rho0 = rho0_gcm3 * GCM3
    return rho0 * G ** 3 * b.Mc ** 2 / c ** 6


def psi_halo(f, b, rho0_gcm3):
    """Eq. (4.18): cloud self-gravity, -3PN,  x^(-11/3)."""
    return (25.0 * np.pi / 924.0) * _dm_prefac(b, rho0_gcm3) \
        * x_of_f(f, b) ** (-11.0 / 3.0)


def _acc_mass_factor(b, include=(1, 2)):
    """Sum_i (m_i^3 / mu^2 m)(3 + 2 m_i^2 / (m mu)) over included BHs."""
    tot = 0.0
    for i in include:
        mi = b.m1 if i == 1 else b.m2
        tot += mi ** 3 / (b.mu ** 2 * b.m) * (3.0 + 2.0 * mi ** 2 / (b.m * b.mu))
    return tot


def psi_acc_high(f, b, rho0_gcm3, include=(1, 2)):
    """Eq. (4.19), high-frequency branch (f > f_acc,i): -5.5PN, x^(-16/3).
    Proportional to the bulk density rho0."""
    return -(25.0 * np.pi / 38912.0) * _dm_prefac(b, rho0_gcm3) \
        * _acc_mass_factor(b, include) * x_of_f(f, b) ** (-16.0 / 3.0)


def psi_acc_low(f, b, rhoa_gcm3, include=(1, 2)):
    """Eq. (4.19), low-frequency branch (f < f_acc,i): -4PN, x^(-13/3).
    Proportional to rho_a; bracket terms -> 1 for f << f_acc (Eq. 5.10)."""
    mfac = sum((3.0 + 2.0 * (b.m1 if i == 1 else b.m2) ** 2 / (b.m * b.mu))
               for i in include)
    return -(75.0 * np.pi * FSTAR / 26624.0) * b.nu ** 0.4 \
        * _dm_prefac(b, rhoa_gcm3) * mfac * x_of_f(f, b) ** (-13.0 / 3.0)


def psi_df(f, b, rho0_gcm3, f_plus):
    """Eq. (4.20), main window f_df^- < f < f_df^+ (smaller BH only):
    -5.5PN carrier x^(-16/3) modulated by the Coulomb-log bracket."""
    x = x_of_f(f, b)
    r = f / f_plus
    bracket = 1.0 + (304.0 / 105.0) * np.log(r) \
        - (361.0 / 105.0) * r ** (16.0 / 3.0) \
        + (256.0 / 105.0) * r ** (19.0 / 3.0)
    mass2 = b.m2 ** 3 / (b.mu ** 2 * b.m)
    return (875.0 * np.pi / 11829248.0) * _dm_prefac(b, rho0_gcm3) \
        * mass2 * x ** (-16.0 / 3.0) * bracket

# ======================================================================
# 4.  Fisher machinery  (Eq. 5.3, phase-only, amplitude decorrelated)
# ======================================================================
def make_fgrid(fmin, fmax, n=6000):
    return np.logspace(np.log10(fmin), np.log10(fmax), n)


def fisher(derivs, fgrid, snr):
    """Gamma_ij = SNR^2 * int w dPsi_i dPsi_j / int w,  w = f^-7/3 / Sn."""
    w = fgrid ** (-7.0 / 3.0) / Sn_LISA(fgrid)
    norm = np.trapezoid(w, fgrid)
    n = len(derivs)
    Gam = np.empty((n, n))
    for i in range(n):
        for j in range(i, n):
            Gam[i, j] = Gam[j, i] = \
                snr ** 2 * np.trapezoid(w * derivs[i] * derivs[j], fgrid) / norm
    return Gam


def invert_fisher(Gam):
    """Numerically stable inversion via correlation-normalised Fisher.
    Returns (covariance, sigmas, correlation matrix, condition number)."""
    d = np.sqrt(np.diag(Gam))
    D = np.outer(d, d)
    C = Gam / D                       # unit-diagonal Fisher
    cond = np.linalg.cond(C)
    Cinv = np.linalg.inv(C)
    Sigma = Cinv / D                  # covariance
    sig = np.sqrt(np.diag(Sigma))
    corr = Sigma / np.outer(sig, sig)
    return Sigma, sig, corr, cond


def binary_param_derivs(b, fgrid):
    """Analytic d/dtc, d/dphic + numeric d/dln m1, d/dln m2 of Psi_vac."""
    d_tc = 2.0 * np.pi * fgrid
    d_phic = -np.ones_like(fgrid)
    eps = 1e-6
    out = []
    for which in ('m1', 'm2'):
        bp = Binary((b.m1 / Msun) * (1 + eps) if which == 'm1' else b.m1 / Msun,
                    (b.m2 / Msun) * (1 + eps) if which == 'm2' else b.m2 / Msun)
        bm = Binary((b.m1 / Msun) * (1 - eps) if which == 'm1' else b.m1 / Msun,
                    (b.m2 / Msun) * (1 - eps) if which == 'm2' else b.m2 / Msun)
        out.append((psi_vacuum(fgrid, bp) - psi_vacuum(fgrid, bm)) / (2 * eps))
    return d_tc, d_phic, out[0], out[1]

# ======================================================================
# 5.  Per-system analysis
# ======================================================================
def analyse_system(name, m1, m2, snr, fdfplus_over_fmax=10.0, verbose=True):
    b = Binary(m1, m2)
    fmin, fmax = b.lisa_band()
    fgrid = make_fgrid(fmin, fmax)

    # ---- fiducial self-interaction: put the DF window around the band
    f_plus = fdfplus_over_fmax * fmax
    y = b.y_for_fdf_plus(f_plus)
    f_minus = b.f_df_minus(y)
    facc1, facc2 = b.f_acc(1, y), b.f_acc(2, y)

    # which BHs are in the HIGH-frequency accretion regime over the band?
    acc_include = tuple(i for i, fa in ((1, facc1), (2, facc2)) if fa < fmin)
    regime_ok = dict(
        df_window=(f_minus < fmin and f_plus > fmax),
        acc_high_1=(facc1 < fmin), acc_high_2=(facc2 < fmin),
        df_active=(b.nu < 0.16 or m1 / m2 > 2.6))

    # ---- mechanism templates: dPsi/drho at rho = 1 g/cm^3 (linear)
    tA = psi_acc_high(fgrid, b, 1.0, include=acc_include if acc_include else (2,))
    tB = psi_df(fgrid, b, 1.0, f_plus)
    tH = psi_halo(fgrid, b, 1.0)
    tL = psi_acc_low(fgrid, b, 1.0)

    d_tc, d_phic, d_lnm1, d_lnm2 = binary_param_derivs(b, fgrid)
    base = [d_tc, d_phic, d_lnm1, d_lnm2]

    # ---- (a) single-mechanism detection thresholds (paper's analysis)
    single = {}
    for lab, t in (('acc', tA), ('df', tB), ('halo', tH), ('acc_low', tL)):
        Gam = fisher(base + [t], fgrid, snr)
        _, sig, _, _ = invert_fisher(Gam)
        single[lab] = sig[4]                    # sigma(rho) in g/cm^3

    # ---- (b) JOINT accretion + dynamical friction (the new question)
    Gam6 = fisher(base + [tA, tB], fgrid, snr)
    Sigma6, sig6, corr6, cond6 = invert_fisher(Gam6)
    rAB = corr6[4, 5]
    degr_A = sig6[4] / single['acc']
    degr_B = sig6[5] / single['df']

    # ---- (c) DM-only joint (no binary-parameter marginalisation)
    Gam2 = fisher([tA, tB], fgrid, snr)
    _, _, corr2, _ = invert_fisher(Gam2)
    rAB_nomarg = corr2[0, 1]

    # ---- (d) full 4-mechanism shape-correlation matrix (marginalised)
    labels4 = ['halo(-3PN)', 'acc_low(-4PN)', 'acc_high(-5.5PN)', 'df(-5.5PN+log)']
    GamM = fisher(base + [tH, tL, tA, tB], fgrid, snr)
    try:
        _, _, corrM, condM = invert_fisher(GamM)
        mech_corr = corrM[4:, 4:]
    except np.linalg.LinAlgError:
        mech_corr, condM = None, np.inf

    res = dict(name=name, m1=m1, m2=m2, snr=snr, fmin=fmin, fmax=fmax,
               y=y, cs_over_c=1.0 / np.sqrt(y), f_plus=f_plus,
               f_minus=f_minus, facc1=facc1, facc2=facc2,
               acc_include=acc_include, regime_ok=regime_ok,
               sigma_single=single, sigma_joint_A=sig6[4],
               sigma_joint_B=sig6[5], rAB=rAB, rAB_nomarg=rAB_nomarg,
               degr_A=degr_A, degr_B=degr_B, cond6=cond6,
               mech_corr=mech_corr, mech_labels=labels4,
               binary=b, fgrid=fgrid, templates=dict(A=tA, B=tB, H=tH, L=tL),
               Sigma6=Sigma6)

    if verbose:
        print_report(res)
    return res


def print_report(r):
    b = r['binary']
    print(f"\n{'=' * 72}\n  {r['name']}:  m1 = {r['m1']:.3g} Msun,  "
          f"m2 = {r['m2']:.3g} Msun,  SNR = {r['snr']:.3g}")
    print(f"{'=' * 72}")
    print(f"  band            : [{r['fmin']:.3e}, {r['fmax']:.3e}] Hz   "
          f"(f_obs 4yr = {b.f_obs():.3e}, f_gamma = {b.f_gamma():.3e})")
    print(f"  fiducial y      : {r['y']:.3e}   (c_s/c = {r['cs_over_c']:.3e})")
    print(f"  DF window       : [{r['f_minus']:.3e}, {r['f_plus']:.3e}] Hz"
          f"   covers band: {r['regime_ok']['df_window']}")
    print(f"  f_acc(BH1,BH2)  : {r['facc1']:.3e}, {r['facc2']:.3e} Hz"
          f"   high-f accretion BHs included: {r['acc_include']}")
    print("\n  -- single-mechanism 1-sigma detection thresholds "
          "(marginalised over tc, phic, ln m1, ln m2) --")
    for k, v in r['sigma_single'].items():
        print(f"     sigma(rho0) [{k:8s}] = {v:.3e} g/cm^3")
    print("\n  -- JOINT accretion + dynamical friction --")
    print(f"     sigma(rho_A)  joint  = {r['sigma_joint_A']:.3e} g/cm^3"
          f"   (x {r['degr_A']:.1f} degradation)")
    print(f"     sigma(rho_B)  joint  = {r['sigma_joint_B']:.3e} g/cm^3"
          f"   (x {r['degr_B']:.1f} degradation)")
    print(f"     r_AB (marginalised)  = {r['rAB']:+.6f}")
    print(f"     r_AB (DM-only)       = {r['rAB_nomarg']:+.6f}")
    print(f"     cond(norm. Fisher)   = {r['cond6']:.3e}")
    if r['mech_corr'] is not None:
        print("\n  -- 4-mechanism correlation matrix (marginalised) --")
        print("     " + "  ".join(f"{l:>16s}" for l in r['mech_labels']))
        for lab, row in zip(r['mech_labels'], r['mech_corr']):
            print(f"     {lab:>16s} " +
                  " ".join(f"{v:+16.3f}" for v in row))

# ======================================================================
# 6.  Parameter sweeps
# ======================================================================
def sweep_mass(q=1e4, snr=30.0, n=16):
    """|r_AB| and thresholds vs primary mass at fixed mass ratio."""
    m1s = np.logspace(4, 7, n)
    rows = []
    for m1 in m1s:
        b = Binary(m1, m1 / q)
        fmin, fmax = b.lisa_band()
        if fmax <= fmin * 1.5:
            continue
        r = analyse_system(f"m1={m1:.2e}", m1, m1 / q, snr, verbose=False)
        rows.append((m1, r['rAB'], r['rAB_nomarg'],
                     r['sigma_single']['acc'], r['degr_A'], r['cond6']))
    return np.array(rows)


def sweep_fdfplus(name, m1, m2, snr, n=15):
    """|r_AB| vs location of the DF threshold f_df^+ relative to the band.
    This is the physically meaningful knob: it sets how strongly the
    Coulomb-log modulation varies across the band."""
    ratios = np.logspace(0.05, 3.0, n)     # f_df^+ / fmax from ~1.1 to 1000
    rows = []
    for R in ratios:
        r = analyse_system(name, m1, m2, snr, fdfplus_over_fmax=R,
                           verbose=False)
        rows.append((R, r['rAB'], r['rAB_nomarg'], r['degr_A']))
    return np.array(rows)

# ======================================================================
# 7.  Validation checks
# ======================================================================
def validate():
    print("\n" + "#" * 72 + "\n#  VALIDATION\n" + "#" * 72)

    # (1) noise curve sanity: sqrt(Sn) minimum should be a few x 1e-21
    #     near ~4-10 mHz (RCL Fig. 1)
    fg = np.logspace(-5, 0, 2000)
    s = np.sqrt(Sn_LISA(fg))
    imin = np.argmin(s)
    print(f"  [noise] min sqrt(Sn) = {s[imin]:.3e} Hz^-1/2 "
          f"at f = {fg[imin]:.3e} Hz  (RCL sky-averaged floor ~1.2e-20)")

    # (2) vacuum-phase sanity: leading term ~ x^(-5/3)
    b = Binary(1e6, 5e5)
    f0 = 1e-3
    x = x_of_f(f0, b)
    lead = 3.0 / 128.0 * x ** (-5 / 3)
    full = psi_vacuum(f0, b)
    print(f"  [vacuum] Mc = {b.Mc/Msun:.4g} Msun; Psi_lead = {lead:.4e}, "
          f"Psi_1PN/Psi_lead - 1 = {full/lead - 1:.3e}")

    # (3) ratio checks against paper Eqs. (4.21), (4.23), (4.27)
    #     evaluated at f = 1 Hz, rho0 = 1 g/cm^3, solar-mass-scale binary
    bb = Binary(2.0, 1.0)          # m> = 2, m< = 1
    f0 = 1.0
    ratio_halo = psi_halo(f0, bb, 1.0) / (3 / 128 * x_of_f(f0, bb) ** (-5 / 3))
    print(f"  [4.21]  Psi_halo/Psi_gw = {ratio_halo:.2e}  (paper ~2e-8, "
          f"mass-independent)")
    ratio_acc = abs(psi_acc_high(f0, bb, 1.0, include=(1,))) \
        / (3 / 128 * x_of_f(f0, bb) ** (-5 / 3))
    est_423 = 0.1 * (2.0) ** 4 * (2.0) ** (-5.0 / 3.0)
    print(f"  [4.23]  |Psi_acc,>|/Psi_gw = {ratio_acc:.2e}  "
          f"(paper order-of-magnitude estimate {est_423:.2e})")

    # (4) MBBH threshold benchmark: paper finds rho0* ~ 8e-13 g/cm^3
    #     (LISA, SNR = 3e4).  Comparable masses -> no dynamical friction.
    r = analyse_system("LISA-MBBH benchmark", 1e6, 5e5, 3e4, verbose=False)
    print(f"  [Table IV] MBBH sigma(rho0)_acc = "
          f"{r['sigma_single']['acc']:.2e} g/cm^3  "
          f"(paper Fisher result ~8e-13; same order expected)")
    return r

# ======================================================================
# 8.  Main
# ======================================================================


# ======================================================================
# ANALYSIS DRIVER (tables, sweeps, CSVs)
# ======================================================================
def run_analysis():
    validate()

    # ---- Boudon Table II/III LISA events with dynamical friction ----
    systems = [
        ("LISA-IMRI", 1.0e4, 10.0, 64.0),
        ("LISA-EMRI", 1.0e5, 10.0, 22.0),
    ]
    results = [analyse_system(*s) for s in systems]

    # ---- sweeps ------------------------------------------------------
    print("\n" + "#" * 72 + "\n#  SWEEP 1: |r_AB| vs primary mass "
          "(q = 1e4, SNR = 30)\n" + "#" * 72)
    ms = sweep_mass()
    for m1, rab, rab0, sig, deg, cond in ms:
        print(f"   m1 = {m1:9.3e}  r_AB = {rab:+.6f}  "
              f"(DM-only {rab0:+.6f})   degr x{deg:6.1f}   cond {cond:.2e}")

    print("\n" + "#" * 72 + "\n#  SWEEP 2: r_AB vs DF-threshold location "
          "f_df^+/fmax (EMRI)\n" + "#" * 72)
    fs = sweep_fdfplus("LISA-EMRI", 1e5, 10.0, 22.0)
    for R, rab, rab0, deg in fs:
        print(f"   f_df^+/fmax = {R:8.2f}   r_AB = {rab:+.6f}   "
              f"(DM-only {rab0:+.6f})   degr x{deg:6.1f}")

    # ---- write CSV ---------------------------------------------------
    with open("results_systems.csv", "w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["system", "m1_Msun", "m2_Msun", "SNR", "fmin_Hz",
                    "fmax_Hz", "y", "sigma_rho_acc_single", "sigma_rho_df_single",
                    "sigma_rho_halo_single", "sigma_rho_accLow_single",
                    "sigma_rho_acc_joint", "sigma_rho_df_joint",
                    "r_AB_marg", "r_AB_DMonly", "degradation_A",
                    "degradation_B", "cond_number"])
        for r in results:
            w.writerow([r['name'], r['m1'], r['m2'], r['snr'], r['fmin'],
                        r['fmax'], r['y'], r['sigma_single']['acc'],
                        r['sigma_single']['df'], r['sigma_single']['halo'],
                        r['sigma_single']['acc_low'], r['sigma_joint_A'],
                        r['sigma_joint_B'], r['rAB'], r['rAB_nomarg'],
                        r['degr_A'], r['degr_B'], r['cond6']])
    np.savetxt("sweep_mass.csv", ms, delimiter=",",
               header="m1_Msun,r_AB_marg,r_AB_DMonly,sigma_rho_acc,degradation,cond")
    np.savetxt("sweep_fdfplus.csv", fs, delimiter=",",
               header="fdfplus_over_fmax,r_AB_marg,r_AB_DMonly,degradation")
    print("\nCSV written: results_systems.csv, sweep_mass.csv, sweep_fdfplus.csv")

# ======================================================================
# FIGURES
# ======================================================================
def make_all_figures():
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    plt.rcParams.update({
        "font.size": 11, "axes.grid": True, "grid.alpha": 0.3,
        "figure.dpi": 150, "savefig.bbox": "tight",
    })

    # ----------------------------------------------------------------------
    # Fig 1: LISA sensitivity + observation bands
    # ----------------------------------------------------------------------
    fg = np.logspace(-5, 0, 3000)
    fig, ax = plt.subplots(figsize=(7, 5))
    ax.loglog(fg, np.sqrt(Sn_LISA(fg)), "k-", lw=1.8,
              label="Robson–Cornish–Liu 2019\n(instr. + 4-yr galactic confusion)")
    for (nm, m1, m2, col) in [("IMRI $10^4+10\\,M_\\odot$", 1e4, 10, "tab:blue"),
                              ("EMRI $10^5+10\\,M_\\odot$", 1e5, 10, "tab:red"),
                              ("MBBH $10^6+5{\\times}10^5$", 1e6, 5e5, "tab:green")]:
        b = Binary(m1, m2)
        lo, hi = b.lisa_band()
        ax.axvspan(lo, hi, alpha=0.12, color=col)
        ax.plot([lo, hi], [np.sqrt(Sn_LISA(lo)), np.sqrt(Sn_LISA(hi))],
                "o", ms=5, color=col, label=f"{nm} band")
    ax.set_xlabel("frequency  $f$  [Hz]")
    ax.set_ylabel(r"$\sqrt{S_n(f)}$  [Hz$^{-1/2}$]")
    ax.set_title("LISA sensitivity and 4-yr observation bands")
    ax.legend(fontsize=8.5, loc="upper right")
    fig.savefig("fig1_noise_bands.png")
    plt.close(fig)

    # ----------------------------------------------------------------------
    # Fig 2: mechanism template shapes (the physical origin of the result)
    # ----------------------------------------------------------------------
    b = Binary(1e5, 10.0)                       # LISA-EMRI
    fmin, fmax = b.lisa_band()
    f = np.logspace(np.log10(fmin), np.log10(fmax), 500)
    f_plus = 10.0 * fmax

    tH = np.abs(psi_halo(f, b, 1.0))
    tL = np.abs(psi_acc_low(f, b, 1.0))
    tA = np.abs(psi_acc_high(f, b, 1.0, include=(1, 2)))
    tB = np.abs(psi_df(f, b, 1.0, f_plus))

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(11, 4.6))
    for t, lab, sty in [(tH, "halo gravity  $\\propto f^{-11/3}$  ($-3$PN)", "-"),
                        (tL, "accretion (low-$f$)  $\\propto f^{-13/3}$  ($-4$PN)", "-"),
                        (tA, "accretion (high-$f$)  $\\propto f^{-16/3}$  ($-5.5$PN)", "-"),
                        (tB, "dyn. friction  $\\propto f^{-16/3}[1+\\log]$  ($-5.5$PN)", "--")]:
        ax1.loglog(f, t / t[0], sty, lw=2, label=lab)
    ax1.set_xlabel("$f$  [Hz]")
    ax1.set_ylabel(r"$|\partial\Psi/\partial\rho|$  (normalised at $f_{\min}$)")
    ax1.set_title("Mechanism dephasing templates (LISA-EMRI band)")
    ax1.legend(fontsize=8.2)

    # fractional shape difference between the two -5.5PN mechanisms
    ratio = (tB / tB[0]) / (tA / tA[0])
    ax2.semilogx(f, ratio, "k-", lw=2)
    ax2.set_xlabel("$f$  [Hz]")
    ax2.set_ylabel("DF template / accretion template\n(both normalised)")
    ax2.set_title("Only the Coulomb log separates the two:\n"
                  f"shape ratio varies by {100*(ratio.max()/ratio.min()-1):.0f}% "
                  "across the band")
    fig.savefig("fig2_templates.png")
    plt.close(fig)

    # ----------------------------------------------------------------------
    # Fig 3: r_AB and degradation vs primary mass
    # ----------------------------------------------------------------------
    ms = sweep_mass(q=1e4, snr=30.0, n=16)
    fig, ax = plt.subplots(figsize=(7, 5))
    ax.semilogx(ms[:, 0], 1.0 - np.abs(ms[:, 1]), "o-", color="tab:red",
                label=r"$1-|r_{AB}|$  (marginalised over $t_c,\Phi_c,\ln m_1,\ln m_2$)")
    ax.semilogx(ms[:, 0], 1.0 - np.abs(ms[:, 2]), "s--", color="tab:blue",
                label=r"$1-|r_{AB}|$  (DM parameters only)")
    ax.set_yscale("log")
    ax.set_xlabel(r"primary mass  $m_1$  [$M_\odot$]   (mass ratio $q=10^4$)")
    ax.set_ylabel(r"$1-|r_{AB}|$")
    ax.set_title("Accretion vs dynamical-friction degeneracy across the LISA band")
    ax2 = ax.twinx()
    ax2.semilogx(ms[:, 0], ms[:, 4], "^:", color="tab:gray", alpha=0.8)
    ax2.set_ylabel(r"threshold degradation  $\sigma_{\rm joint}/\sigma_{\rm single}"
                   r"=(1-r_{AB}^2)^{-1/2}$", color="tab:gray")
    ax2.tick_params(axis="y", colors="tab:gray")
    ax.legend(fontsize=9, loc="center left")
    fig.savefig("fig3_rAB_vs_mass.png")
    plt.close(fig)

    # ----------------------------------------------------------------------
    # Fig 4: joint (rho_A, rho_B) error ellipse for LISA-EMRI
    # ----------------------------------------------------------------------
    r = analyse_system("LISA-EMRI", 1e5, 10.0, 22.0, verbose=False)
    S = r["Sigma6"][4:, 4:]                     # 2x2 covariance of (rho_A, rho_B)
    vals, vecs = np.linalg.eigh(S)
    th = np.linspace(0, 2 * np.pi, 400)
    circ = np.stack([np.cos(th), np.sin(th)])
    ell = vecs @ (np.sqrt(np.maximum(vals, 0.0))[:, None] * circ)   # 1-sigma

    fig, ax = plt.subplots(figsize=(6.2, 5.6))
    ax.plot(ell[0], ell[1], "b-", lw=2, label=r"$1\sigma$ joint ellipse")
    ax.axvline(0, color="k", lw=0.6)
    ax.axhline(0, color="k", lw=0.6)
    sA, sB = r["sigma_joint_A"], r["sigma_joint_B"]
    ax.errorbar([0], [0], xerr=[[r["sigma_single"]["acc"]], [r["sigma_single"]["acc"]]],
                yerr=[[r["sigma_single"]["df"]], [r["sigma_single"]["df"]]],
                fmt="r+", ms=12, capsize=4,
                label=r"single-mechanism $1\sigma$")
    ax.set_xlabel(r"$\rho_A$ (accretion)  [g cm$^{-3}$]")
    ax.set_ylabel(r"$\rho_B$ (dyn. friction)  [g cm$^{-3}$]")
    ax.set_title(f"LISA-EMRI joint constraint:  $r_{{AB}}={r['rAB']:+.5f}$\n"
                 "the ellipse collapses onto an unresolvable degeneracy direction")
    ax.legend(fontsize=9)
    ax.ticklabel_format(style="sci", scilimits=(0, 0))
    fig.savefig("fig4_ellipse.png")
    plt.close(fig)

    # ----------------------------------------------------------------------
    # Fig 5: r_AB vs DF threshold placement
    # ----------------------------------------------------------------------
    fs = sweep_fdfplus("LISA-EMRI", 1e5, 10.0, 22.0)
    fig, ax = plt.subplots(figsize=(7, 5))
    ax.loglog(fs[:, 0], 1.0 - np.abs(fs[:, 1]), "o-", color="tab:red",
              label=r"$1-|r_{AB}|$ (marginalised)")
    ax.loglog(fs[:, 0], 1.0 - np.abs(fs[:, 2]), "s--", color="tab:blue",
              label=r"$1-|r_{AB}|$ (DM only)")
    ax.set_xlabel(r"$f_{\rm df}^{+}/f_{\max}$   (sets the density ratio "
                  r"$y=\rho_a/\rho_0$ via Eq. 5.7)")
    ax.set_ylabel(r"$1-|r_{AB}|$")
    ax.set_title("Degeneracy vs dynamical-friction threshold placement (LISA-EMRI)\n"
                 "distinguishability is best when the log turnover sits in-band")
    ax.legend(fontsize=9)
    fig.savefig("fig5_rAB_vs_threshold.png")
    plt.close(fig)

    print("figures written: fig1_noise_bands.png, fig2_templates.png, "
          "fig3_rAB_vs_mass.png, fig4_ellipse.png, fig5_rAB_vs_threshold.png")


run_analysis()
make_all_figures()

from IPython.display import Image, display
for i, name in enumerate(["fig1_noise_bands", "fig2_templates",
                          "fig3_rAB_vs_mass", "fig4_ellipse",
                          "fig5_rAB_vs_threshold"], 1):
    print(f"Figure {i}: {name}")
    display(Image(f"{name}.png"))